### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [navidshaikh/scanner-rpm-verify#1]
Hi!
what would be the license for this repo?

**Comment by navidshaikh** [comment]
hello, it should be Apache License Version 2.0, adding one.

**Comment by navidshaikh** [comment]
@pombredanne : added the license to master branch https://github.com/navidshaikh/scanner-rpm-verify/commit/48dab389c490d102218429cd3373fd240e6285de let me know if that works for you. thanks!

**Comment by pombredanne** [comment]
@navidshaikh thank you ++ for the swift reply!
:bow:
